name: Create release package

on:
  create:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Create venv
        run: make venv
      
      - name: Run linter
        run: make lint
      
      - name: Run Tests
        run: make tests